### Numpy Array and Basics

In [27]:
import numpy as np

### Creating Array From list

In [46]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,4],[3,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 4]
 [3 5 6]]


### List vs Numpy Array

In [29]:
pylist = [1,2,3]
print("Python List Multiplication:", pylist*2)
pyarray = np.array([1,2,3])
print("Python List Multiplication:", pyarray*2)

Python List Multiplication: [1, 2, 3, 1, 2, 3]
Python List Multiplication: [2 4 6]


In [22]:
py_list = [i*2 for i in range(1000000)]
print(py_list[0:10])

np_array = np.arange(1000000)*2
print(np_array[0:10])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Array operation time:", time.time() - start)



 List operation time: 0.12639546394348145

 Array operation time: 0.008166313171386719


### Creating Array from scratch

In [44]:
zeros = np.zeros((3,4))
print(zeros)
print("-----------------------")
ones = np.ones((3,4))
print(ones)
print("-----------------------")
full = np.full((2,2),7)
print(full)
print("-----------------------")
random = np.random.random((2,3))
print(random)
print("-----------------------")
sequence = np.arange(0,10,2)
print(sequence)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----------------------
[[7 7]
 [7 7]]
-----------------------
[[0.03031527 0.81218371 0.10773724]
 [0.63864823 0.35934188 0.12626987]]
-----------------------
[0 2 4 6 8]


### Vector, Matrix and Tensor

In [60]:
vector = np.array([1,2,3])
print(vector) 

matrix = np.array([[1,2,3],
           [4,5,6]])
print(matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor*2)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


### Array Properties

In [67]:
arr = np.array([[1,2,3],
                [4,5,6], 
                [7,8,True],
                [9,10,11.1],
                [12,"13","Asmet"]])

print("Shape: ", arr.shape)
print("Dimensions",arr.ndim) #1d / 2d
print("Size:", arr.size)
print("Datatype:", arr.dtype)

Shape:  (5, 3)
Dimensions 2
Size: 15
Datatype: <U32


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original Array : ", arr)

reshape = arr.reshape((3,4))
print("Reshaped Array :", reshape)

flattened = reshape.flatten()
print("Flattened Array : ", flattened)

#ravel (returns view of the original array, instead of copy)
raveled = reshape.ravel()
print("Raveled Array:", raveled)

#Transpose ( an array where the rows and columns are swapped)
transpose = reshape.T
print("Transposed Array:", transpose)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
