### Numpy Array Operations

In [13]:
import numpy as np

In [8]:
# 1D Array
arr = np.arange(1,11)
print(arr)
print("Basic Slicing :", arr[2:7])
print("With Step Slicing :", arr[1:8:2])
print("Negative Indexing :", arr[-4])



[ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing : [3 4 5 6 7]
With Step Slicing : [2 4 6 8]
Negative Indexing : 7


In [ ]:
#2D Array
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element:", arr_2d[1,2])
# arr_2d[1,2] --> 1 defines [4,5,6],
#                 2 defines 6 as its in 2nd Index

print("Entire row:", arr_2d[0])
#Prints --> Entire row: [1 2 3]

print("Entire column:", arr_2d[:,-1])
#Prints --> Entire column: [3 6 9]

Specific Element: 6
Entire row: [1 2 3]
Entire column: [3 6 9]


### Sorting 

In [14]:
unsorted_arr = np.array([1,6,7,9,3,4,2,5])

print("Sorted Array: " , np.sort(unsorted_arr))

arr_2d_unsorted = np.array([[3,1],[1,2],[3,3]])
print("Sorted 2d Array by Column : ",np.sort(arr_2d_unsorted, axis=0))
#Top to Bottom
print("Sorted 2d Array by Row : ",np.sort(arr_2d_unsorted, axis=1))
#Left to Right

Sorted Array:  [1 2 3 4 5 6 7 9]
Sorted 2d Array by Column :  [[1 1]
 [3 2]
 [3 3]]
Sorted 2d Array by Row :  [[1 3]
 [1 2]
 [3 3]]


## Filter of data

In [15]:
number = np.arange(1,11)
even_number = number[number % 2 == 0]
print("Even Numbers:", even_number)

Even Numbers: [ 2  4  6  8 10]


# Filter with mask

In [16]:
mask = number > 5
print("Numbers greater than 5 :", number[mask])

Numbers greater than 5 : [ 6  7  8  9 10]


# Fancy Indexing vs np.where()

In [ ]:
print(number)
print("...............................")

indices = [0,2,4]
print(f"The Value at Index {indices} are : {number[indices]}")

print("...............................")

where_result = np.where(number>5)
print("NP where:", number[where_result])

[ 1  2  3  4  5  6  7  8  9 10]
...............................
The Value at Index [0, 2, 4] are : [1 3 5]
...............................
NP where: [ 6  7  8  9 10]


# Condition (used in ML, type of if else)

In [56]:
condition_array = np.where (number >= 5, number *4, number)
print(condition_array)

[ 1  2  3  4 20 24 28 32 36 40]


# Adding and removing data

In [73]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

add =  arr1 + arr2 
print(add) # Addition
arrayAND = arr1 & arr2 # Using AND Bitwise Op
print(arrayAND)
arrayOR = arr1 | arr2 # Using OR Bitwise Op
print(arrayOR)

concatenate = np.concatenate((arr1,arr2))
print((concatenate)) #[1 2 3 4 5 6]


deleted = np.delete(concatenate,5)
print("Array after Deletion: ", deleted)



[5 7 9]
[0 0 2]
[5 7 7]
[1 2 3 4 5 6]
Array after Deletion:  [1 2 3 4 5]


# Compatibilty of Arrays

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8])

print("Compatibilty Shapes:", a.shape == b.shape == c.shape)

Compatibilty Shapes: False


# Adding Column and Rows

In [69]:
original = np.array([[1,2,3],[4,5,6]])
print("Original Row is --> \n" ,original)

add_row = np.array([[7,8,9]])
new_row = np.vstack((original,add_row)) 
print("The Array after adding row is --> \n",new_row) 

add_col= np.array([[10],[11],[12]])
new_col = np.hstack((new_row,add_col)) 
print("The Array after adding Column is --> \n",new_col) 

Original Row is --> 
 [[1 2 3]
 [4 5 6]]
The Array after adding row is --> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Array after adding Column is --> 
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
