In [2]:
import cv2
import numpy as np
import os

In [14]:
img = cv2.imread("images/Screenshot 2024-12-22 180436.png")
#Resize of image
resize = cv2.resize(img,(400,500))
cv2.imshow("Founder of S8UL",resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("images/Screenshot 2024-12-22 180436.png")
print(img)  #rgb (0-255,0-255,0-255)

[[[ 22  40  71]
  [ 22  40  71]
  [ 22  40  71]
  ...
  [ 43  72 114]
  [ 44  74 115]
  [ 46  76 117]]

 [[ 22  40  71]
  [ 22  40  71]
  [ 22  40  71]
  ...
  [ 45  75 117]
  [ 44  74 115]
  [ 43  73 114]]

 [[ 22  40  71]
  [ 22  40  71]
  [ 22  40  71]
  ...
  [ 46  75 117]
  [ 43  73 114]
  [ 40  70 111]]

 ...

 [[ 38  70  47]
  [ 39  71  48]
  [ 40  71  48]
  ...
  [ 40  74  50]
  [ 39  73  50]
  [ 39  73  49]]

 [[ 38  70  47]
  [ 39  71  48]
  [ 40  72  48]
  ...
  [ 39  73  49]
  [ 39  73  49]
  [ 39  73  49]]

 [[ 38  71  46]
  [ 39  71  47]
  [ 40  72  47]
  ...
  [ 38  72  49]
  [ 39  73  49]
  [ 39  73  49]]]


In [16]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [17]:
#Multiple image using numpy in opencv

img = cv2.imread("images/Screenshot 2024-12-22 180436.png")
#Resize of image
resize = cv2.resize(img,(500,500))
h = np.hstack((resize,resize))
cv2.imshow("Founder of S8UL",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
#Multiple image using numpy in opencv

img = cv2.imread("images/Screenshot 2024-12-22 180436.png")
#Resize of image
resize = cv2.resize(img,(300,300))
v = np.vstack((resize,resize))
cv2.imshow("Founder of S8UL",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
#Multiple image using numpy in opencv

img = cv2.imread("images/Screenshot 2024-12-22 180436.png")
#Resize of image
resize = cv2.resize(img,(300,300))
h = np.hstack((resize,resize,resize))
v = np.vstack((h,h))
cv2.imshow("Founder of S8UL",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
list_name = os.listdir(r"D:\Python\OpenCV\images")
list_name


#Slideshow

for name in list_name:
    path = "D:\\Python\\OpenCV\\images"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(500,600))
    cv2.imshow("Images",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()



In [18]:
img = cv2.imread(r"images\Screenshot 2024-12-23 114732.png")
# print(img)  #rgb (0-255,0-255,0-255)
print(img.shape) #(774, 894, 3) - 3 here is the rgb
img = cv2.resize(img,(500,500))
cv2.imshow("Pictures",img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

(793, 796, 3)


In [16]:
# cv2.IMREAD_COLOR --> 1 (No flag needed)

img = cv2.imread(r"images\Screenshot 2024-12-23 114732.png",1)
# print(img)  #rgb (0-255,0-255,0-255)
print(img.shape) #(774, 894, 3) - 3 here is the rgb
img = cv2.resize(img,(500,500))
cv2.imshow("Pictures",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(793, 796, 3)


In [17]:
# cv2.IMREAD_GRAYSCALE --> 0 (Black and White Image)

img = cv2.imread(r"images\Screenshot 2024-12-23 114732.png",0)
# print(img)  #rgb (0-255,0-255,0-255)
print(img.shape) #(774, 894, 3) - 3 here is the rgb
img = cv2.resize(img,(500,500))
cv2.imshow("Pictures",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(793, 796)


In [15]:
# cv2.IMREAD_UNCHANGED --> -1 (Nothing changes --> Alpha parameter)

img = cv2.imread(r"images\Screenshot 2024-12-23 114732.png",-1)
# print(img)  #rgb (0-255,0-255,0-255)
print(img.shape) #(774, 894, 3) - 3 here is the rgb
img = cv2.resize(img,(500,500))
cv2.imshow("Pictures",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(793, 796, 4)
